In [1]:
import pandas as pd
import numpy as np

In [5]:
# dictionayからSeriesを作成
data = {
    'Name': 'John',
    'Sex': 'male',
    'Age': 22
}

In [6]:
pd.Series(data)

Name    John
Sex     male
Age       22
dtype: object

In [15]:
# Numpy ArrayからSeriesを作成
array = np.array([22, 31, 42, 23])
age_series = pd.Series(array)

In [16]:
array = np.array(['John', 'male', 22])
john_series = pd.Series(array, index=['Name', 'Sex', 'Age'])

In [17]:
john_series['Name']

'John'

In [18]:
age_series.values

array([22, 31, 42, 23])

In [19]:
age_series.mean()

29.5

## DataFrame

In [23]:
# Numpy array から作成
ndarray = np.arange(10).reshape(2, 5)
ndarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
pd.DataFrame(ndarray, index=['index1', 'index2'], columns=['a', 'b', 'c', 'd', 'e'])

        a  b  c  d  e
index1  0  1  2  3  4
index2  5  6  7  8  9

In [31]:
data = {
    'name': ['John', 'Zack', 'Emily'],
    'sex': ['male', 'male', 'female'],
    'age': [22, 30, 32]
}
df = pd.DataFrame(data)

In [32]:
df

    name     sex  age
0   John    male   22
1   Zack    male   30
2  Emily  female   32

In [2]:
## pd.read_csv()
df = pd.read_csv('dataset/tmdb_5000_movies.csv')

In [5]:
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [35]:
len(df)

4803

In [6]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [7]:
type(df.describe())

pandas.core.frame.DataFrame

In [8]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [12]:
df['revenue']

0       2787965087
1        961000000
2        880674609
3       1084939099
4        284139100
           ...
4798       2040920
4799             0
4800             0
4801             0
4802             0
Name: revenue, Length: 4803, dtype: int64

In [13]:
df.revenue # 非推奨（→　スペースがあるカラムに対応できない。.~は本来関数を呼び出すもの。）

0       2787965087
1        961000000
2        880674609
3       1084939099
4        284139100
           ...
4798       2040920
4799             0
4800             0
4801             0
4802             0
Name: revenue, Length: 4803, dtype: int64

In [14]:
df[['revenue', 'original_title', 'budget']]

         revenue                            original_title     budget
0     2787965087                                    Avatar  237000000
1      961000000  Pirates of the Caribbean: At World's End  300000000
2      880674609                                   Spectre  245000000
3     1084939099                     The Dark Knight Rises  250000000
4      284139100                               John Carter  260000000
...          ...                                       ...        ...
4798     2040920                               El Mariachi     220000
4799           0                                 Newlyweds       9000
4800           0                 Signed, Sealed, Delivered          0
4801           0                          Shanghai Calling          0
4802           0                         My Date with Drew          0

[4803 rows x 3 columns]

In [16]:
df[['revenue']]

         revenue
0     2787965087
1      961000000
2      880674609
3     1084939099
4      284139100
...          ...
4798     2040920
4799           0
4800           0
4801           0
4802           0

[4803 rows x 1 columns]

In [19]:
df.iloc[10:13]['original_title']

10                              Superman Returns
11                             Quantum of Solace
12    Pirates of the Caribbean: Dead Man's Chest
Name: original_title, dtype: object

In [20]:
df = pd.read_csv('dataset/tmdb_5000_movies.csv')

In [21]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [23]:
df.drop('id', axis=1)

,budget,genres,homepage,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [24]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [25]:
df = df.drop(0)

In [26]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

## Filter

In [30]:
data = {
    'name': ['John', 'Zack', 'Emily'],
    'sex': ['male', 'male', 'female'],
    'age': [22, 30, 32]
}
df = pd.DataFrame(data)
df

    name     sex  age
0   John    male   22
1  fZack    male   30
2  Emily  female   32

In [32]:
df[[True, False, True]]

    name     sex  age
0   John    male   22
2  Emily  female   32

In [34]:
filter_series = pd.Series([True, False, True])
filter_series

0     True
1    False
2     True
dtype: bool

In [35]:
df[filter_series]

    name     sex  age
0   John    male   22
2  Emily  female   32

In [38]:
filter_s = df['age'] >= 30

In [40]:
df[filter_s]

    name     sex  age
1  fZack    male   30
2  Emily  female   32

In [42]:
df = pd.read_csv('dataset/tmdb_5000_movies.csv')

In [54]:
df[(df['original_language'] == 'ja') & (df['vote_average'] > 8)]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
1987,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
2247,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
4535,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878

In [51]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [57]:
# 予算(budget)が0もしくは売り上げ(revenue)が0の映画

In [59]:
df[(df['budget'] == 0) | (df['revenue'] == 0)]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
83,27000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,79698,[],en,The Lovers,The Lovers is an epic romance time travel adve...,2.418535,"[{""name"": ""Corsan"", ""id"": 7299}, {""name"": ""Bli...","[{""iso_3166_1"": ""AU"", ""name"": ""Australia""}, {""...",2015-02-13,0,109.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Love is longer than life.,The Lovers,4.8,34
135,150000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 27, ""name...",http://www.thewolfmanmovie.com/,7978,"[{""id"": 494, ""name"": ""father son relationship""...",en,The Wolfman,"Lawrence Talbot, an American man on a visit to...",21.214571,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-02-11,0,102.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,When the moon is full the legend comes to life,The Wolfman,5.5,549
265,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 14, ""nam...",NaN,10588,"[{""id"": 977, ""name"": ""cat""}, {""id"": 1155, ""nam...",en,The Cat in the Hat,Conrad and Sally Walden are home alone with th...,18.251129,"[{""name"": ""Imagine Entertainment"", ""id"": 23}, ...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2003-11-21,0,82.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Don't mess with the hat.,The Cat in the Hat,4.9,366
309,84000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 35, ""na...",NaN,10214,"[{""id"": 1009, ""name"": ""baby""}, {""id"": 2546, ""n...",en,Son of the Mask,"Tim Avery, an aspiring cartoonist, finds himse...",17.815595,"[{""name"": ""New Line Cinema"", ""id"": 12}, {""name...","[{""iso_3166_1"": ""DE"", ""name"": ""Germany""}, {""is...",2005-02-18,0,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Who's next?,Son of the Mask,3.6,338
321,0,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,77953,"[{""id"": 6078, ""name"": ""politics""}, {""id"": 6083...",en,The Campaign,Two rival politicians compete to win an electi...,16.460356,"[{""name"": ""Everyman Pictures"", ""id"": 2242}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-08-09,104907746,85.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,May The Best Loser Win.,The Campaign,5.6,578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4797,0,"[{""id"": 10769, ""name"": ""Foreign""}, {""id"": 53, ...",NaN,67238,[],en,Cavite,"Adam, a security guard, travels from Californi...",0.022173,[],[],2005-03-12,0,80.0,[],Released,NaN,Cavite,7.5,2
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [60]:
# 予算も売り上げも0ではない

In [62]:
# df[(df['budget'] != 0) & (df['revenue'] != 0)]
df[~((df['budget'] == 0) | (df['revenue'] == 0))]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4773,27000,"[{""id"": 35, ""name"": ""Comedy""}]",http://www.miramax.com/movie/clerks/,2292,"[{""id"": 1361, ""name"": ""salesclerk""}, {""id"": 30...",en,Clerks,Convenience and video store clerks Dante and R...,19.748658,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1994-09-13,3151130,92.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Just because they serve you doesn't mean they ...,Clerks,7.4,755
4788,12000,"[{""id"": 27, ""name"": ""Horror""}, {""id"": 35, ""nam...",NaN,692,"[{""id"": 237, ""name"": ""gay""}, {""id"": 900, ""name...",en,Pink Flamingos,Notorious Baltimore criminal and underground f...,4.553644,"[{""name"": ""Dreamland Productions"", ""id"": 407}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",1972-03-12,6000000,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,An exercise in poor taste.,Pink Flamingos,6.2,110
4792,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63
4796,7000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.primermovie.com,14337,"[{""id"": 1448, ""name"": ""distrust""}, {""id"": 2101...",en,Primer,Friends/fledgling entrepreneurs invent a devic...,23.307949,"[{""name"": ""Thinkfilm"", ""id"": 446}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-10-08,424760,77.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,What happens if it actually works?,Primer,6.9,658
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238

In [63]:
df = pd.read_csv('dataset/tmdb_5000_movies.csv')

In [64]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [68]:
df = df[df['original_language'] == 'ja']

In [69]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
97,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
1471,41677699,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,12429,"[{""id"": 456, ""name"": ""mother""}, {""id"": 1357, ""...",ja,崖の上のポニョ,"The son of a sailor, 5-year old Sosuke lives a...",39.586760,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2008-07-19,187479518,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Welcome To A World Where Anything Is Possible.,Ponyo,7.5,926
1709,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
1987,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
2247,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
2258,20000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 14, ""...",NaN,8953,"[{""id"": 392, ""name"": ""england""}, {""id"": 1436, ...",ja,Steamboy,After receiving a package from his Grandfather...,9.129808,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-07-17,0,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He will save the future.,Steamboy,6.4,102
2294,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
2888,12000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.office-kitano.co.jp/brother/index.html,327,"[{""id"": 380, ""name"": ""brother brother relation...",ja,Brother,A Japanese Yakuza gangster’s deadly existence ...,5.327714,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2000-09-09,15250000,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Are You Japanese?,Brother,6.8,107
2900,12000000,"[{""id"": 878, ""name"": ""Science Fiction""}]",NaN,61984,[],ja,Space Battleship Yamato,"In 2199, five years after the Gamilons began a...",5.158067,"[{""name"": ""Tokyo Broadcasting System (TBS)"", ""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2010-12-01,11212294,131.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Battleship Yamato,6.3,59
2908,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,13889,[],ja,まあだだよ,This film tells the story of professor Uehida ...,2.930853,"[{""name"": ""Tokuma Shoten"", ""id"": 1779}, {""name...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1993-04-17,0,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Madadayo,7.5,20
3296,8000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.bandaivisual.co.jp/akira/,149,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",ja,アキラ,Childhood friends Tetsuo and Kaneda are pulled...,39.338097,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1988-07-16,553171,124.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Neo-Tokyo is about to E.X.P.L.O.D.E.,Akira,7.8,773
3542,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.r-100.com/,193722,"[{""id"": 7089, ""name"": ""dominatrix""}, {""id"": 15...",ja,R100,Ruthless dominatrixes pursue a mild-mannered s...,3.213920,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-10-05,0,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,M For Father,R100,5.4,31
3901,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://movies.warnerbros.com/pk3/,10991,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 280...",ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,9.188850,"[{""name"": ""TV Tokyo"", ""id"": 3034}, {""name"": ""4...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2000-07-08,68411275,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,5.9,137
4344,1000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 27, ""...",NaN,10643,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1299, ""n...",ja,Gojira ni-sen mireniamu,Godzilla saves Tokyo from a flying saucer that...,3.322721,"[{""name"": ""Toho Film (Eiga) Co. Ltd."", ""id"": 6...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1999-12-11,10037390,107.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Get ready to crumble.,Godzilla 2000,5.9,43
4535,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878
4792,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63

In [79]:
df.reset_index(drop=True)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
1,41677699,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,12429,"[{""id"": 456, ""name"": ""mother""}, {""id"": 1357, ""...",ja,崖の上のポニョ,"The son of a sailor, 5-year old Sosuke lives a...",39.586760,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2008-07-19,187479518,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Welcome To A World Where Anything Is Possible.,Ponyo,7.5,926
2,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
3,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
4,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
5,20000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 14, ""...",NaN,8953,"[{""id"": 392, ""name"": ""england""}, {""id"": 1436, ...",ja,Steamboy,After receiving a package from his Grandfather...,9.129808,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-07-17,0,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He will save the future.,Steamboy,6.4,102
6,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
7,12000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.office-kitano.co.jp/brother/index.html,327,"[{""id"": 380, ""name"": ""brother brother relation...",ja,Brother,A Japanese Yakuza gangster’s deadly existence ...,5.327714,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2000-09-09,15250000,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Are You Japanese?,Brother,6.8,107
8,12000000,"[{""id"": 878, ""name"": ""Science Fiction""}]",NaN,61984,[],ja,Space Battleship Yamato,"In 2199, five years after the Gamilons began a...",5.158067,"[{""name"": ""Tokyo Broadcasting System (TBS)"", ""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2010-12-01,11212294,131.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Battleship Yamato,6.3,59
9,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,13889,[],ja,まあだだよ,This film tells the story of professor Uehida ...,2.930853,"[{""name"": ""Tokuma Shoten"", ""id"": 1779}, {""name...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1993-04-17,0,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Madadayo,7.5,20
10,8000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.bandaivisual.co.jp/akira/,149,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",ja,アキラ,Childhood friends Tetsuo and Kaneda are pulled...,39.338097,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1988-07-16,553171,124.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Neo-Tokyo is about to E.X.P.L.O.D.E.,Akira,7.8,773
11,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.r-100.com/,193722,"[{""id"": 7089, ""name"": ""dominatrix""}, {""id"": 15...",ja,R100,Ruthless dominatrixes pursue a mild-mannered s...,3.213920,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-10-05,0,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,M For Father,R100,5.4,31
12,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://movies.warnerbros.com/pk3/,10991,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 280...",ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,9.188850,"[{""name"": ""TV Tokyo"", ""id"": 3034}, {""name"": ""4...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2000-07-08,68411275,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,5.9,137
13,1000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 27, ""...",NaN,10643,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1299, ""n...",ja,Gojira ni-sen mireniamu,Godzilla saves Tokyo from a flying saucer that...,3.322721,"[{""name"": ""Toho Film (Eiga) Co. Ltd."", ""id"": 6...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1999-12-11,10037390,107.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Get ready to crumble.,Godzilla 2000,5.9,43
14,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878
15,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63

In [80]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
1,41677699,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,12429,"[{""id"": 456, ""name"": ""mother""}, {""id"": 1357, ""...",ja,崖の上のポニョ,"The son of a sailor, 5-year old Sosuke lives a...",39.586760,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2008-07-19,187479518,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Welcome To A World Where Anything Is Possible.,Ponyo,7.5,926
2,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
3,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
4,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
5,20000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 14, ""...",NaN,8953,"[{""id"": 392, ""name"": ""england""}, {""id"": 1436, ...",ja,Steamboy,After receiving a package from his Grandfather...,9.129808,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-07-17,0,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He will save the future.,Steamboy,6.4,102
6,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
7,12000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.office-kitano.co.jp/brother/index.html,327,"[{""id"": 380, ""name"": ""brother brother relation...",ja,Brother,A Japanese Yakuza gangster’s deadly existence ...,5.327714,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2000-09-09,15250000,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Are You Japanese?,Brother,6.8,107
8,12000000,"[{""id"": 878, ""name"": ""Science Fiction""}]",NaN,61984,[],ja,Space Battleship Yamato,"In 2199, five years after the Gamilons began a...",5.158067,"[{""name"": ""Tokyo Broadcasting System (TBS)"", ""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2010-12-01,11212294,131.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Battleship Yamato,6.3,59
9,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,13889,[],ja,まあだだよ,This film tells the story of professor Uehida ...,2.930853,"[{""name"": ""Tokuma Shoten"", ""id"": 1779}, {""name...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1993-04-17,0,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Madadayo,7.5,20
10,8000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.bandaivisual.co.jp/akira/,149,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",ja,アキラ,Childhood friends Tetsuo and Kaneda are pulled...,39.338097,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1988-07-16,553171,124.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Neo-Tokyo is about to E.X.P.L.O.D.E.,Akira,7.8,773
11,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.r-100.com/,193722,"[{""id"": 7089, ""name"": ""dominatrix""}, {""id"": 15...",ja,R100,Ruthless dominatrixes pursue a mild-mannered s...,3.213920,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-10-05,0,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,M For Father,R100,5.4,31
12,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://movies.warnerbros.com/pk3/,10991,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 280...",ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,9.188850,"[{""name"": ""TV Tokyo"", ""id"": 3034}, {""name"": ""4...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2000-07-08,68411275,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,5.9,137
13,1000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 27, ""...",NaN,10643,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1299, ""n...",ja,Gojira ni-sen mireniamu,Godzilla saves Tokyo from a flying saucer that...,3.322721,"[{""name"": ""Toho Film (Eiga) Co. Ltd."", ""id"": 6...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1999-12-11,10037390,107.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Get ready to crumble.,Godzilla 2000,5.9,43
14,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878
15,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63

In [75]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
1,41677699,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,12429,"[{""id"": 456, ""name"": ""mother""}, {""id"": 1357, ""...",ja,崖の上のポニョ,"The son of a sailor, 5-year old Sosuke lives a...",39.586760,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2008-07-19,187479518,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Welcome To A World Where Anything Is Possible.,Ponyo,7.5,926
2,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
3,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
4,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
5,20000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 14, ""...",NaN,8953,"[{""id"": 392, ""name"": ""england""}, {""id"": 1436, ...",ja,Steamboy,After receiving a package from his Grandfather...,9.129808,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-07-17,0,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He will save the future.,Steamboy,6.4,102
6,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
7,12000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.office-kitano.co.jp/brother/index.html,327,"[{""id"": 380, ""name"": ""brother brother relation...",ja,Brother,A Japanese Yakuza gangster’s deadly existence ...,5.327714,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2000-09-09,15250000,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Are You Japanese?,Brother,6.8,107
8,12000000,"[{""id"": 878, ""name"": ""Science Fiction""}]",NaN,61984,[],ja,Space Battleship Yamato,"In 2199, five years after the Gamilons began a...",5.158067,"[{""name"": ""Tokyo Broadcasting System (TBS)"", ""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2010-12-01,11212294,131.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Battleship Yamato,6.3,59
9,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,13889,[],ja,まあだだよ,This film tells the story of professor Uehida ...,2.930853,"[{""name"": ""Tokuma Shoten"", ""id"": 1779}, {""name...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1993-04-17,0,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Madadayo,7.5,20
10,8000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.bandaivisual.co.jp/akira/,149,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",ja,アキラ,Childhood friends Tetsuo and Kaneda are pulled...,39.338097,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1988-07-16,553171,124.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Neo-Tokyo is about to E.X.P.L.O.D.E.,Akira,7.8,773
11,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.r-100.com/,193722,"[{""id"": 7089, ""name"": ""dominatrix""}, {""id"": 15...",ja,R100,Ruthless dominatrixes pursue a mild-mannered s...,3.213920,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-10-05,0,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,M For Father,R100,5.4,31
12,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://movies.warnerbros.com/pk3/,10991,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 280...",ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,9.188850,"[{""name"": ""TV Tokyo"", ""id"": 3034}, {""name"": ""4...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2000-07-08,68411275,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,5.9,137
13,1000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 27, ""...",NaN,10643,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1299, ""n...",ja,Gojira ni-sen mireniamu,Godzilla saves Tokyo from a flying saucer that...,3.322721,"[{""name"": ""Toho Film (Eiga) Co. Ltd."", ""id"": 6...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1999-12-11,10037390,107.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Get ready to crumble.,Godzilla 2000,5.9,43
14,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878
15,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63

In [76]:
df

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,15000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",NaN,315011,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 7671,...",ja,シン・ゴジラ,From the mind behind Evangelion comes a hit la...,9.476999,"[{""name"": ""Cine Bazar"", ""id"": 5896}, {""name"": ...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2016-07-29,77000000,120.0,"[{""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""is...",Released,A god incarnate. A city doomed.,Shin Godzilla,6.5,143
1,41677699,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",NaN,12429,"[{""id"": 456, ""name"": ""mother""}, {""id"": 1357, ""...",ja,崖の上のポニョ,"The son of a sailor, 5-year old Sosuke lives a...",39.586760,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2008-07-19,187479518,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Welcome To A World Where Anything Is Possible.,Ponyo,7.5,926
2,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
3,24000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 16, ""na...",NaN,4935,"[{""id"": 334, ""name"": ""flying""}, {""id"": 616, ""n...",ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",49.549984,"[{""name"": ""Studio Ghibli"", ""id"": 10342}, {""nam...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-11-19,234710455,119.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The two lived there,Howl's Moving Castle,8.2,1991
4,26500000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,128,"[{""id"": 1721, ""name"": ""fight""}, {""id"": 1994, ""...",ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",60.732738,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-07-12,159375308,134.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,8.2,1983
5,20000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 14, ""...",NaN,8953,"[{""id"": 392, ""name"": ""england""}, {""id"": 1436, ...",ja,Steamboy,After receiving a package from his Grandfather...,9.129808,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2004-07-17,0,126.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,He will save the future.,Steamboy,6.4,102
6,15000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""na...",http://movies.disney.com/spirited-away,129,"[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""na...",ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,118.968562,"[{""name"": ""Studio Ghibli"", ""id"": 10342}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2001-07-20,274925095,125.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,8.3,3840
7,12000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name...",http://www.office-kitano.co.jp/brother/index.html,327,"[{""id"": 380, ""name"": ""brother brother relation...",ja,Brother,A Japanese Yakuza gangster’s deadly existence ...,5.327714,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2000-09-09,15250000,114.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Are You Japanese?,Brother,6.8,107
8,12000000,"[{""id"": 878, ""name"": ""Science Fiction""}]",NaN,61984,[],ja,Space Battleship Yamato,"In 2199, five years after the Gamilons began a...",5.158067,"[{""name"": ""Tokyo Broadcasting System (TBS)"", ""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2010-12-01,11212294,131.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Battleship Yamato,6.3,59
9,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,13889,[],ja,まあだだよ,This film tells the story of professor Uehida ...,2.930853,"[{""name"": ""Tokuma Shoten"", ""id"": 1779}, {""name...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1993-04-17,0,134.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Madadayo,7.5,20
10,8000000,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://www.bandaivisual.co.jp/akira/,149,"[{""id"": 83, ""name"": ""saving the world""}, {""id""...",ja,アキラ,Childhood friends Tetsuo and Kaneda are pulled...,39.338097,"[{""name"": ""Bandai Visual Company"", ""id"": 528},...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1988-07-16,553171,124.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Neo-Tokyo is about to E.X.P.L.O.D.E.,Akira,7.8,773
11,5500000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.r-100.com/,193722,"[{""id"": 7089, ""name"": ""dominatrix""}, {""id"": 15...",ja,R100,Ruthless dominatrixes pursue a mild-mannered s...,3.213920,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-10-05,0,100.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,M For Father,R100,5.4,31
12,16000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://movies.warnerbros.com/pk3/,10991,"[{""id"": 1262, ""name"": ""mountains""}, {""id"": 280...",ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,9.188850,"[{""name"": ""TV Tokyo"", ""id"": 3034}, {""name"": ""4...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2000-07-08,68411275,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown,5.9,137
13,1000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 27, ""...",NaN,10643,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1299, ""n...",ja,Gojira ni-sen mireniamu,Godzilla saves Tokyo from a flying saucer that...,3.322721,"[{""name"": ""Toho Film (Eiga) Co. Ltd."", ""id"": 6...","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1999-12-11,10037390,107.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Get ready to crumble.,Godzilla 2000,5.9,43
14,2000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,346,"[{""id"": 233, ""name"": ""japan""}, {""id"": 1462, ""n...",ja,七人の侍,A samurai answers a village's request for prot...,39.756748,"[{""name"": ""Toho Company"", ""id"": 882}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1954-04-26,271841,207.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,The Mighty Warriors Who Became the Seven Natio...,Seven Samurai,8.2,878
15,20000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 27, ""name...",NaN,36095,"[{""id"": 233, ""name"": ""japan""}, {""id"": 549, ""na...",ja,キュア,A wave of gruesome murders is sweeping Tokyo. ...,0.212443,"[{""name"": ""Daiei Studios"", ""id"": 881}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",1997-11-06,99000,111.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,Madness. Terror. Murder.,Cure,7.4,63

In [81]:
df = pd.read_csv('dataset/tmdb_5000_movies.csv')

In [88]:
df = df.set_index('id').head(3)

In [89]:
df.loc[19995]

budget                                                          237000000
genres                  [{"id": 28, "name": "Action"}, {"id": 12, "nam...
homepage                                      http://www.avatarmovie.com/
keywords                [{"id": 1463, "name": "culture clash"}, {"id":...
original_language                                                      en
original_title                                                     Avatar
overview                In the 22nd century, a paraplegic Marine is di...
popularity                                                        150.438
production_companies    [{"name": "Ingenious Film Partners", "id": 289...
production_countries    [{"iso_3166_1": "US", "name": "United States o...
release_date                                                   2009-12-10
revenue                                                        2787965087
runtime                                                               162
spoken_languages        [{"iso_639_1": "en", "name": "English"}, {"iso...
status                                                           Released
tagline                                       Enter the World of Pandora.
title                                                              Avatar
vote_average                                                          7.2
vote_count                                                          11800
Name: 19995, dtype: object